//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbInvitacionBodaEntities : DbContext
    {
        public dbInvitacionBodaEntities()
            : base("name=dbInvitacionBodaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcompanantes> tblAcompanantes { get; set; }
        public virtual DbSet<tblBebidas> tblBebidas { get; set; }
        public virtual DbSet<tblBebidasInvitado> tblBebidasInvitado { get; set; }
        public virtual DbSet<tblBebidasNovios> tblBebidasNovios { get; set; }
        public virtual DbSet<tblBioNovios> tblBioNovios { get; set; }
        public virtual DbSet<tblConfiguracion> tblConfiguracion { get; set; }
        public virtual DbSet<tblCuentasCorreo> tblCuentasCorreo { get; set; }
        public virtual DbSet<tblEnviosDiarios> tblEnviosDiarios { get; set; }
        public virtual DbSet<tblHistoriaNovios> tblHistoriaNovios { get; set; }
        public virtual DbSet<tblIdioma> tblIdioma { get; set; }
        public virtual DbSet<tblIntentosIngreso> tblIntentosIngreso { get; set; }
        public virtual DbSet<tblInvitados> tblInvitados { get; set; }
        public virtual DbSet<tblItinerario> tblItinerario { get; set; }
        public virtual DbSet<tblMensajesWA> tblMensajesWA { get; set; }
        public virtual DbSet<tblMesasNovios> tblMesasNovios { get; set; }
        public virtual DbSet<tblMesasRegalos> tblMesasRegalos { get; set; }
        public virtual DbSet<tblNovios> tblNovios { get; set; }
        public virtual DbSet<tblPlantillaBoletos> tblPlantillaBoletos { get; set; }
        public virtual DbSet<tblPlantillas> tblPlantillas { get; set; }
        public virtual DbSet<tblPlantillasNovios> tblPlantillasNovios { get; set; }
        public virtual DbSet<tblTipoInvitado> tblTipoInvitado { get; set; }
        public virtual DbSet<tblEmpresas> tblEmpresas { get; set; }
        public virtual DbSet<tblWeddingPlanners> tblWeddingPlanners { get; set; }
        public virtual DbSet<tblWPNovios> tblWPNovios { get; set; }
    }
}
