//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbInvitacionBodaEntities : DbContext
    {
        public dbInvitacionBodaEntities()
            : base("name=dbInvitacionBodaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAcompanantes> tblAcompanantes { get; set; }
        public virtual DbSet<tblBebidas> tblBebidas { get; set; }
        public virtual DbSet<tblBebidasInvitado> tblBebidasInvitado { get; set; }
        public virtual DbSet<tblBebidasNovios> tblBebidasNovios { get; set; }
        public virtual DbSet<tblBioNovios> tblBioNovios { get; set; }
        public virtual DbSet<tblConfiguracion> tblConfiguracion { get; set; }
        public virtual DbSet<tblCuentasCorreo> tblCuentasCorreo { get; set; }
        public virtual DbSet<tblEnviosDiarios> tblEnviosDiarios { get; set; }
        public virtual DbSet<tblHistoriaNovios> tblHistoriaNovios { get; set; }
        public virtual DbSet<tblIdioma> tblIdioma { get; set; }
        public virtual DbSet<tblIntentosIngreso> tblIntentosIngreso { get; set; }
        public virtual DbSet<tblInvitados> tblInvitados { get; set; }
        public virtual DbSet<tblMensajesWA> tblMensajesWA { get; set; }
        public virtual DbSet<tblMesasNovios> tblMesasNovios { get; set; }
        public virtual DbSet<tblMesasRegalos> tblMesasRegalos { get; set; }
        public virtual DbSet<tblNovios> tblNovios { get; set; }
        public virtual DbSet<tblPlantillaBoletos> tblPlantillaBoletos { get; set; }
        public virtual DbSet<tblPlantillas> tblPlantillas { get; set; }
        public virtual DbSet<tblPlantillasNovios> tblPlantillasNovios { get; set; }
        public virtual DbSet<tblTipoInvitado> tblTipoInvitado { get; set; }
        public virtual DbSet<tblCategoriasProveedores> tblCategoriasProveedores { get; set; }
        public virtual DbSet<tblDieteticas> tblDieteticas { get; set; }
        public virtual DbSet<tblEstados> tblEstados { get; set; }
        public virtual DbSet<tblMensajesProveedores> tblMensajesProveedores { get; set; }
        public virtual DbSet<tblMunicipios> tblMunicipios { get; set; }
        public virtual DbSet<tblOfertasProveedores> tblOfertasProveedores { get; set; }
        public virtual DbSet<tblPreguntasProveedores> tblPreguntasProveedores { get; set; }
        public virtual DbSet<tblProveedoresDieteticas> tblProveedoresDieteticas { get; set; }
        public virtual DbSet<tblProveedoresMunicipios> tblProveedoresMunicipios { get; set; }
        public virtual DbSet<tblRedesProveedores> tblRedesProveedores { get; set; }
        public virtual DbSet<tblRedesSociales> tblRedesSociales { get; set; }
        public virtual DbSet<tblRespuestasProveedores> tblRespuestasProveedores { get; set; }
        public virtual DbSet<tblSeleccionarOfertas> tblSeleccionarOfertas { get; set; }
        public virtual DbSet<tblServiciosCategoriasProvedores> tblServiciosCategoriasProvedores { get; set; }
        public virtual DbSet<tblServiciosProveedores> tblServiciosProveedores { get; set; }
        public virtual DbSet<tblEmpresasOrganizadores> tblEmpresasOrganizadores { get; set; }
        public virtual DbSet<tblOrganizadoresBodas> tblOrganizadoresBodas { get; set; }
        public virtual DbSet<tblSeleccionarOrganizadoresBodas> tblSeleccionarOrganizadoresBodas { get; set; }
        public virtual DbSet<tblItinerarios> tblItinerarios { get; set; }
        public virtual DbSet<tblStatusPagos> tblStatusPagos { get; set; }
        public virtual DbSet<tblProductosProveedores> tblProductosProveedores { get; set; }
        public virtual DbSet<tblPresupuestos> tblPresupuestos { get; set; }
        public virtual DbSet<tblProveedores> tblProveedores { get; set; }
        public virtual DbSet<tblTipoUsuarios> tblTipoUsuarios { get; set; }
        public virtual DbSet<tblUsuarios> tblUsuarios { get; set; }
    }
}
