//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBebidasNovios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBebidasNovios()
        {
            this.tblBebidasInvitado = new HashSet<tblBebidasInvitado>();
        }
    
        public int idBebidaNovios { get; set; }
        public Nullable<int> idBebida { get; set; }
        public Nullable<int> idNovios { get; set; }
    
        public virtual tblBebidas tblBebidas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBebidasInvitado> tblBebidasInvitado { get; set; }
        public virtual tblNovios tblNovios { get; set; }
    }
}
