//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBebidasInvitado
    {
        public int idBebidaInvitado { get; set; }
        public Nullable<int> idBebidaNovios { get; set; }
        public Nullable<int> idInvitado { get; set; }
    
        public virtual tblBebidasNovios tblBebidasNovios { get; set; }
        public virtual tblInvitados tblInvitados { get; set; }
    }
}
