//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpresasOrganizadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpresasOrganizadores()
        {
            this.tblOrganizadoresBodas = new HashSet<tblOrganizadoresBodas>();
        }
    
        public int idEmpresaOrganizador { get; set; }
        public string nombreEmpresa { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public string telefono { get; set; }
        public string paginaWeb { get; set; }
    
        public virtual tblEstados tblEstados { get; set; }
        public virtual tblMunicipios tblMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrganizadoresBodas> tblOrganizadoresBodas { get; set; }
    }
}
