//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoriaNovios
    {
        public int idNoviosHistoria { get; set; }
        public Nullable<System.DateTime> fechaConocieron { get; set; }
        public string conocieron { get; set; }
        public string imgConocieron { get; set; }
        public Nullable<int> idNovios { get; set; }
        public Nullable<System.DateTime> fechaPropuesta { get; set; }
        public string propuesta { get; set; }
        public string imgPropuesta { get; set; }
        public Nullable<System.DateTime> fechaPrimeraCita { get; set; }
        public string primeraCita { get; set; }
        public string imgPrimeraCita { get; set; }
        public Nullable<System.DateTime> fechaPedida { get; set; }
        public string pedida { get; set; }
        public string imgPedida { get; set; }
        public Nullable<System.DateTime> fechaNovios { get; set; }
        public string novios { get; set; }
        public string imgNovios { get; set; }
    
        public virtual tblNovios tblNovios { get; set; }
    }
}
