//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvitados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInvitados()
        {
            this.tblAcompanantes = new HashSet<tblAcompanantes>();
            this.tblBebidasInvitado = new HashSet<tblBebidasInvitado>();
        }
    
        public int idInvitado { get; set; }
        public string apodo { get; set; }
        public string nombre { get; set; }
        public string aPaterno { get; set; }
        public string aMaterno { get; set; }
        public Nullable<int> boletos { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> boletosConfirmados { get; set; }
        public string correo { get; set; }
        public Nullable<int> idTipoInvitado { get; set; }
        public Nullable<int> vienePor { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idTipoMenu { get; set; }
        public Nullable<System.DateTime> accedio { get; set; }
        public Nullable<System.DateTime> llegoWeb { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> invitacionEnviada { get; set; }
        public Nullable<bool> soloMisa { get; set; }
        public Nullable<bool> asistira { get; set; }
        public Nullable<bool> qrEnviado { get; set; }
        public Nullable<bool> qrConfirmado { get; set; }
        public Nullable<bool> asistioBoda { get; set; }
        public Nullable<int> mesa { get; set; }
        public Nullable<int> idNovios { get; set; }
        public string mensaje { get; set; }
        public Nullable<bool> regalo { get; set; }
        public string mensajeRegalo { get; set; }
        public Nullable<int> idIdioma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAcompanantes> tblAcompanantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBebidasInvitado> tblBebidasInvitado { get; set; }
        public virtual tblTipoInvitado tblTipoInvitado { get; set; }
        public virtual tblNovios tblNovios { get; set; }
    }
}
