//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMensajesWA
    {
        public int idMensajeWA { get; set; }
        public Nullable<int> idTipoInvitado { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public string mensajeInicial { get; set; }
        public string mensajeMesaRegalos { get; set; }
        public string mensajeDiaD { get; set; }
    }
}
