//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMunicipios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMunicipios()
        {
            this.tblProveedoresMunicipios = new HashSet<tblProveedoresMunicipios>();
            this.tblEmpresasOrganizadores = new HashSet<tblEmpresasOrganizadores>();
        }
    
        public int idMunicipio { get; set; }
        public string nombreMunicipio { get; set; }
        public Nullable<int> idEstado { get; set; }
    
        public virtual tblEstados tblEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProveedoresMunicipios> tblProveedoresMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmpresasOrganizadores> tblEmpresasOrganizadores { get; set; }
    }
}
