//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNovios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNovios()
        {
            this.tblBebidasNovios = new HashSet<tblBebidasNovios>();
            this.tblBioNovios = new HashSet<tblBioNovios>();
            this.tblConfiguracion = new HashSet<tblConfiguracion>();
            this.tblCuentasCorreo = new HashSet<tblCuentasCorreo>();
            this.tblHistoriaNovios = new HashSet<tblHistoriaNovios>();
            this.tblInvitados = new HashSet<tblInvitados>();
            this.tblMesasNovios = new HashSet<tblMesasNovios>();
            this.tblPlantillasNovios = new HashSet<tblPlantillasNovios>();
            this.tblTipoInvitado = new HashSet<tblTipoInvitado>();
            this.tblSeleccionarOrganizadoresBodas = new HashSet<tblSeleccionarOrganizadoresBodas>();
        }
    
        public int idNovios { get; set; }
        public string nombreNovia { get; set; }
        public string aPNovia { get; set; }
        public string aMNovia { get; set; }
        public string nombreNovio { get; set; }
        public string aPNovio { get; set; }
        public string aMNovio { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public string dominio { get; set; }
        public string padrinoNombre { get; set; }
        public string padrinoApellido { get; set; }
        public string madrinaNombre { get; set; }
        public string madrinaApellido { get; set; }
        public string misaLugar { get; set; }
        public string misaHora { get; set; }
        public Nullable<System.DateTime> misaFecha { get; set; }
        public string recepcionLugar { get; set; }
        public string recepcionHora { get; set; }
        public Nullable<System.DateTime> recepcionFecha { get; set; }
        public string fiestaLugar { get; set; }
        public string fiestaHora { get; set; }
        public Nullable<System.DateTime> fiestaFecha { get; set; }
        public string password { get; set; }
        public string correoRegistro { get; set; }
        public string telRegistro { get; set; }
        public Nullable<int> idPlantilla { get; set; }
        public Nullable<bool> activo { get; set; }
        public string papaNovioNombre { get; set; }
        public string mamaNovioNombre { get; set; }
        public string papaNoviaNombre { get; set; }
        public string mamaNoviaNombre { get; set; }
        public string facebookNovio { get; set; }
        public string facebookNovia { get; set; }
        public string twitterNovio { get; set; }
        public string twitterNovia { get; set; }
        public string instagramNovio { get; set; }
        public string instagramNovia { get; set; }
        public Nullable<bool> validacionCorreo { get; set; }
        public string misaLatitud { get; set; }
        public string misaLongitud { get; set; }
        public string recepcionLatitud { get; set; }
        public string recepcionLongitud { get; set; }
        public string fiestaLatitud { get; set; }
        public string fiestaLongitud { get; set; }
        public Nullable<bool> dominioExterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBebidasNovios> tblBebidasNovios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBioNovios> tblBioNovios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblConfiguracion> tblConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCuentasCorreo> tblCuentasCorreo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHistoriaNovios> tblHistoriaNovios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvitados> tblInvitados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMesasNovios> tblMesasNovios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlantillasNovios> tblPlantillasNovios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTipoInvitado> tblTipoInvitado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeleccionarOrganizadoresBodas> tblSeleccionarOrganizadoresBodas { get; set; }
    }
}
