//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganizadoresBodas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrganizadoresBodas()
        {
            this.tblSeleccionarOrganizadoresBodas = new HashSet<tblSeleccionarOrganizadoresBodas>();
        }
    
        public int idOrganizadorBoda { get; set; }
        public Nullable<int> idEmpresaOrganizador { get; set; }
        public string nombreOrganizador { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual tblEmpresasOrganizadores tblEmpresasOrganizadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeleccionarOrganizadoresBodas> tblSeleccionarOrganizadoresBodas { get; set; }
    }
}
