//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlantillaBoletos
    {
        public int idPM_boletos { get; set; }
        public string plantillaBoleto { get; set; }
        public Nullable<decimal> ancho { get; set; }
        public Nullable<decimal> alto { get; set; }
    }
}
