//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPresupuestos
    {
        public int idPresupuesto { get; set; }
        public Nullable<int> idNovios { get; set; }
        public Nullable<int> idServicioCategoProv { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
        public Nullable<int> idStatusPago { get; set; }
        public string descripcion { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> idProductoProveedor { get; set; }
    
        public virtual tblNovios tblNovios { get; set; }
        public virtual tblProductosProveedores tblProductosProveedores { get; set; }
        public virtual tblServiciosProveedores tblServiciosProveedores { get; set; }
        public virtual tblServiciosCategoriasProvedores tblServiciosCategoriasProvedores { get; set; }
        public virtual tblStatusPagos tblStatusPagos { get; set; }
    }
}
