//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlantillasNovios
    {
        public int idPlantillasNovios { get; set; }
        public Nullable<int> idNovios { get; set; }
        public Nullable<int> idPM_invitacion { get; set; }
        public Nullable<int> idPW_invitacion { get; set; }
        public Nullable<int> idPWA_invitacion { get; set; }
        public Nullable<int> idPM_boletos { get; set; }
        public Nullable<int> idPWA_boletos { get; set; }
        public Nullable<int> idPM_urgente { get; set; }
        public Nullable<int> idPWA_urgente { get; set; }
        public Nullable<int> idPM_diaD { get; set; }
        public Nullable<int> idPWA_diaD { get; set; }
    
        public virtual tblNovios tblNovios { get; set; }
    }
}
