//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProveedores()
        {
            this.tblMensajesProveedores = new HashSet<tblMensajesProveedores>();
            this.tblProveedoresMunicipios = new HashSet<tblProveedoresMunicipios>();
            this.tblProveedoresDieteticas = new HashSet<tblProveedoresDieteticas>();
            this.tblRedesProveedores = new HashSet<tblRedesProveedores>();
            this.tblRespuestasProveedores = new HashSet<tblRespuestasProveedores>();
            this.tblSeleccionarOfertas = new HashSet<tblSeleccionarOfertas>();
            this.tblServiciosProveedores = new HashSet<tblServiciosProveedores>();
        }
    
        public int idProveedor { get; set; }
        public string nomNegocio { get; set; }
        public Nullable<int> idCategoriaProveedor { get; set; }
        public string sitioWeb { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string codigoPostal { get; set; }
        public string direccion { get; set; }
        public string pais { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<int> idMunicipio { get; set; }
        public Nullable<decimal> precioInicial { get; set; }
        public Nullable<int> usuarioID { get; set; }
        public string password { get; set; }
    
        public virtual tblCategoriasProveedores tblCategoriasProveedores { get; set; }
        public virtual tblEstados tblEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMensajesProveedores> tblMensajesProveedores { get; set; }
        public virtual tblMunicipios tblMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProveedoresMunicipios> tblProveedoresMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProveedoresDieteticas> tblProveedoresDieteticas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRedesProveedores> tblRedesProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRespuestasProveedores> tblRespuestasProveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSeleccionarOfertas> tblSeleccionarOfertas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiciosProveedores> tblServiciosProveedores { get; set; }
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
