//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRedesProveedores
    {
        public int idRedProveedor { get; set; }
        public Nullable<int> idRedSocial { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public string link { get; set; }
    
        public virtual tblProveedores tblProveedores { get; set; }
        public virtual tblRedesSociales tblRedesSociales { get; set; }
    }
}
