//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IAB_MVC_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeddingPlanners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWeddingPlanners()
        {
            this.tblWPNovios = new HashSet<tblWPNovios>();
        }
    
        public int idWeddingPlanner { get; set; }
        public string nombre { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string correoElectronico1 { get; set; }
        public string correoElectronico2 { get; set; }
        public string telefono { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual tblEmpresas tblEmpresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWPNovios> tblWPNovios { get; set; }
    }
}
